### ISSUE TITLE
ERROR "No decoy hits found, check if the correct decoy prefix was specified with the --decoy_pattern flag"

### ISSUE THREAD

**Issue by yafeng** [statisticalbiotechnology/triqler#31]
Hi @MatthewThe , 
I run into another error after fixed the minimum two conditions errors according to your instruction. 
The error message was:
ERROR: No decoy hits found, check if the correct decoy prefix was specified with the --decoy_pattern flag

However, I have added prefix "decoy_" to the decoy protein hits. I don't understand why it still ask for decoy prefix.
The file was attached in case you want to have a look. Thanks!
[threeProteome-mix-triqler-input.txt.zip](https://github.com/user-attachments/files/18004901/threeProteome-mix-triqler-input.txt.zip)

Yafeng

**Comment by MatthewThe** [comment]
The problem is that you gave all decoys an intensity of 0. 
Rows with 0 intensity are considered as missing values and are not parsed.
Giving these an arbitrary non-zero value, e.g. 0.1 solves this problem and does not affect the protein quantification of target proteins.

Some observations/tips:
- you should remove the `_Decoy` suffix from the protein identifiers, otherwise the picked protein procedure does not work properly.
- proteins should be separated by tabs, not by semicolons. this is an (unfortunate) inheritance from the percolator output format. I will add support for semicolon separated protein strings soon.
- I recommend searching the data with a fasta file without isoforms and unverified proteins. Triqler currently discards all peptides shared by multiple proteins.
- it looks like the input is already filtered at 1% FDR. This will work but for Triqler to work optimally, a 100% FDR search is preferred.
- it is a bit suspicious that all decoy proteins only have a single peptide but I would need to know more about the search engine and parameters to judge properly.

In case you haven't checked it out, Triqler has a user manual that clarifies some of these points: https://www.biorxiv.org/content/10.1101/2020.09.24.311605v1.full
